[tool.poetry]
name = "sml-python-small"
version = "3.0.0"
description = "SML small (pandas methods)"
authors = []

[tool.poetry.dependencies]
python = ">=3.7.1"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
